dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install: 
   - pip3 install --upgrade pip 
   - pip install coveralls
   - npm install lcov-parse

script: 
 python test.py

notifications:
  webhooks:
    - https://stripe-app-3.herokuapp.com/api/v1/challenge/check_builds/
